// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package co.wangming.nsb.rpc.protobuf;

public final class Rpc {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_nscall_framework_protobuf_CallRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_nscall_framework_protobuf_CallRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_nscall_framework_protobuf_Argument_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_nscall_framework_protobuf_Argument_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\trpc.proto\022\035com.nscall.framework.protob" +
                        "uf\"o\n\013CallRequest\022\022\n\nmethodName\030\001 \001(\t\022\021\n" +
                        "\tcallIndex\030\002 \001(\003\0229\n\010argument\030\003 \003(\0132\'.com" +
                        ".nscall.framework.protobuf.Argument\"&\n\010A" +
                        "rgument\022\013\n\003idx\030\001 \001(\005\022\r\n\005value\030\002 \001(\005b\006pro" +
                        "to3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_com_nscall_framework_protobuf_CallRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_nscall_framework_protobuf_CallRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_nscall_framework_protobuf_CallRequest_descriptor,
                new String[]{"MethodName", "CallIndex", "Argument",});
        internal_static_com_nscall_framework_protobuf_Argument_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_com_nscall_framework_protobuf_Argument_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_nscall_framework_protobuf_Argument_descriptor,
                new String[]{"Idx", "Value",});
    }

    private Rpc() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface CallRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.nscall.framework.protobuf.CallRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string methodName = 1;</code>
         */
        String getMethodName();

        /**
         * <code>string methodName = 1;</code>
         */
        com.google.protobuf.ByteString
        getMethodNameBytes();

        /**
         * <code>int64 callIndex = 2;</code>
         */
        long getCallIndex();

        /**
         * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
         */
        java.util.List<Argument>
        getArgumentList();

        /**
         * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
         */
        Rpc.Argument getArgument(int index);

        /**
         * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
         */
        int getArgumentCount();

        /**
         * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
         */
        java.util.List<? extends ArgumentOrBuilder>
        getArgumentOrBuilderList();

        /**
         * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
         */
        Rpc.ArgumentOrBuilder getArgumentOrBuilder(
                int index);
    }

    public interface ArgumentOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.nscall.framework.protobuf.Argument)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 idx = 1;</code>
         */
        int getIdx();

        /**
         * <code>int32 value = 2;</code>
         */
        int getValue();
    }

    /**
     * Protobuf type {@code com.nscall.framework.protobuf.CallRequest}
     */
    public static final class CallRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.nscall.framework.protobuf.CallRequest)
            CallRequestOrBuilder {
        public static final int METHODNAME_FIELD_NUMBER = 1;
        public static final int CALLINDEX_FIELD_NUMBER = 2;
        public static final int ARGUMENT_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:com.nscall.framework.protobuf.CallRequest)
        private static final Rpc.CallRequest DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<CallRequest>
                PARSER = new com.google.protobuf.AbstractParser<CallRequest>() {
            public CallRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new CallRequest(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new Rpc.CallRequest();
        }

        private int bitField0_;
        private volatile Object methodName_;
        private long callIndex_;
        private java.util.List<Argument> argument_;
        private byte memoizedIsInitialized = -1;

        // Use CallRequest.newBuilder() to construct.
        private CallRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private CallRequest() {
            methodName_ = "";
            callIndex_ = 0L;
            argument_ = java.util.Collections.emptyList();
        }

        private CallRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            methodName_ = s;
                            break;
                        }
                        case 16: {

                            callIndex_ = input.readInt64();
                            break;
                        }
                        case 26: {
                            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                                argument_ = new java.util.ArrayList<Argument>();
                                mutable_bitField0_ |= 0x00000004;
                            }
                            argument_.add(
                                    input.readMessage(Rpc.Argument.parser(), extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                    argument_ = java.util.Collections.unmodifiableList(argument_);
                }
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Rpc.internal_static_com_nscall_framework_protobuf_CallRequest_descriptor;
        }

        public static Rpc.CallRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Rpc.CallRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Rpc.CallRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Rpc.CallRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Rpc.CallRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Rpc.CallRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Rpc.CallRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Rpc.CallRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Rpc.CallRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Rpc.CallRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Rpc.CallRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Rpc.CallRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Rpc.CallRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static Rpc.CallRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<CallRequest> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Rpc.internal_static_com_nscall_framework_protobuf_CallRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Rpc.CallRequest.class, Rpc.CallRequest.Builder.class);
        }

        /**
         * <code>string methodName = 1;</code>
         */
        public String getMethodName() {
            Object ref = methodName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                methodName_ = s;
                return s;
            }
        }

        /**
         * <code>string methodName = 1;</code>
         */
        public com.google.protobuf.ByteString
        getMethodNameBytes() {
            Object ref = methodName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                methodName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>int64 callIndex = 2;</code>
         */
        public long getCallIndex() {
            return callIndex_;
        }

        /**
         * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
         */
        public java.util.List<Argument> getArgumentList() {
            return argument_;
        }

        /**
         * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
         */
        public java.util.List<? extends ArgumentOrBuilder>
        getArgumentOrBuilderList() {
            return argument_;
        }

        /**
         * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
         */
        public int getArgumentCount() {
            return argument_.size();
        }

        /**
         * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
         */
        public Rpc.Argument getArgument(int index) {
            return argument_.get(index);
        }

        /**
         * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
         */
        public Rpc.ArgumentOrBuilder getArgumentOrBuilder(
                int index) {
            return argument_.get(index);
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getMethodNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, methodName_);
            }
            if (callIndex_ != 0L) {
                output.writeInt64(2, callIndex_);
            }
            for (int i = 0; i < argument_.size(); i++) {
                output.writeMessage(3, argument_.get(i));
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getMethodNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, methodName_);
            }
            if (callIndex_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(2, callIndex_);
            }
            for (int i = 0; i < argument_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, argument_.get(i));
            }
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Rpc.CallRequest)) {
                return super.equals(obj);
            }
            Rpc.CallRequest other = (Rpc.CallRequest) obj;

            boolean result = true;
            result = result && getMethodName()
                    .equals(other.getMethodName());
            result = result && (getCallIndex()
                    == other.getCallIndex());
            result = result && getArgumentList()
                    .equals(other.getArgumentList());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
            hash = (53 * hash) + getMethodName().hashCode();
            hash = (37 * hash) + CALLINDEX_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getCallIndex());
            if (getArgumentCount() > 0) {
                hash = (37 * hash) + ARGUMENT_FIELD_NUMBER;
                hash = (53 * hash) + getArgumentList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<CallRequest> getParserForType() {
            return PARSER;
        }

        public Rpc.CallRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code com.nscall.framework.protobuf.CallRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.nscall.framework.protobuf.CallRequest)
                Rpc.CallRequestOrBuilder {
            private int bitField0_;
            private Object methodName_ = "";
            private long callIndex_;
            private java.util.List<Argument> argument_ =
                    java.util.Collections.emptyList();
            private com.google.protobuf.RepeatedFieldBuilderV3<
                    Rpc.Argument, Rpc.Argument.Builder, Rpc.ArgumentOrBuilder> argumentBuilder_;

            // Construct using com.nscall.framework.protobuf.Rpc.CallRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Rpc.internal_static_com_nscall_framework_protobuf_CallRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Rpc.internal_static_com_nscall_framework_protobuf_CallRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Rpc.CallRequest.class, Rpc.CallRequest.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getArgumentFieldBuilder();
                }
            }

            public Builder clear() {
                super.clear();
                methodName_ = "";

                callIndex_ = 0L;

                if (argumentBuilder_ == null) {
                    argument_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                } else {
                    argumentBuilder_.clear();
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Rpc.internal_static_com_nscall_framework_protobuf_CallRequest_descriptor;
            }

            public Rpc.CallRequest getDefaultInstanceForType() {
                return Rpc.CallRequest.getDefaultInstance();
            }

            public Rpc.CallRequest build() {
                Rpc.CallRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Rpc.CallRequest buildPartial() {
                Rpc.CallRequest result = new Rpc.CallRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.methodName_ = methodName_;
                result.callIndex_ = callIndex_;
                if (argumentBuilder_ == null) {
                    if (((bitField0_ & 0x00000004) == 0x00000004)) {
                        argument_ = java.util.Collections.unmodifiableList(argument_);
                        bitField0_ = (bitField0_ & ~0x00000004);
                    }
                    result.argument_ = argument_;
                } else {
                    result.argument_ = argumentBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Rpc.CallRequest) {
                    return mergeFrom((Rpc.CallRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Rpc.CallRequest other) {
                if (other == Rpc.CallRequest.getDefaultInstance()) return this;
                if (!other.getMethodName().isEmpty()) {
                    methodName_ = other.methodName_;
                    onChanged();
                }
                if (other.getCallIndex() != 0L) {
                    setCallIndex(other.getCallIndex());
                }
                if (argumentBuilder_ == null) {
                    if (!other.argument_.isEmpty()) {
                        if (argument_.isEmpty()) {
                            argument_ = other.argument_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                        } else {
                            ensureArgumentIsMutable();
                            argument_.addAll(other.argument_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.argument_.isEmpty()) {
                        if (argumentBuilder_.isEmpty()) {
                            argumentBuilder_.dispose();
                            argumentBuilder_ = null;
                            argument_ = other.argument_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                            argumentBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getArgumentFieldBuilder() : null;
                        } else {
                            argumentBuilder_.addAllMessages(other.argument_);
                        }
                    }
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Rpc.CallRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Rpc.CallRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>string methodName = 1;</code>
             */
            public String getMethodName() {
                Object ref = methodName_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    methodName_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string methodName = 1;</code>
             */
            public Builder setMethodName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                methodName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string methodName = 1;</code>
             */
            public com.google.protobuf.ByteString
            getMethodNameBytes() {
                Object ref = methodName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    methodName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string methodName = 1;</code>
             */
            public Builder setMethodNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                methodName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string methodName = 1;</code>
             */
            public Builder clearMethodName() {

                methodName_ = getDefaultInstance().getMethodName();
                onChanged();
                return this;
            }

            /**
             * <code>int64 callIndex = 2;</code>
             */
            public long getCallIndex() {
                return callIndex_;
            }

            /**
             * <code>int64 callIndex = 2;</code>
             */
            public Builder setCallIndex(long value) {

                callIndex_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int64 callIndex = 2;</code>
             */
            public Builder clearCallIndex() {

                callIndex_ = 0L;
                onChanged();
                return this;
            }

            private void ensureArgumentIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    argument_ = new java.util.ArrayList<Argument>(argument_);
                    bitField0_ |= 0x00000004;
                }
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public java.util.List<Argument> getArgumentList() {
                if (argumentBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(argument_);
                } else {
                    return argumentBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public int getArgumentCount() {
                if (argumentBuilder_ == null) {
                    return argument_.size();
                } else {
                    return argumentBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public Rpc.Argument getArgument(int index) {
                if (argumentBuilder_ == null) {
                    return argument_.get(index);
                } else {
                    return argumentBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public Builder setArgument(
                    int index, Rpc.Argument value) {
                if (argumentBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureArgumentIsMutable();
                    argument_.set(index, value);
                    onChanged();
                } else {
                    argumentBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public Builder setArgument(
                    int index, Rpc.Argument.Builder builderForValue) {
                if (argumentBuilder_ == null) {
                    ensureArgumentIsMutable();
                    argument_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    argumentBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public Builder addArgument(Rpc.Argument value) {
                if (argumentBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureArgumentIsMutable();
                    argument_.add(value);
                    onChanged();
                } else {
                    argumentBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public Builder addArgument(
                    int index, Rpc.Argument value) {
                if (argumentBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureArgumentIsMutable();
                    argument_.add(index, value);
                    onChanged();
                } else {
                    argumentBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public Builder addArgument(
                    Rpc.Argument.Builder builderForValue) {
                if (argumentBuilder_ == null) {
                    ensureArgumentIsMutable();
                    argument_.add(builderForValue.build());
                    onChanged();
                } else {
                    argumentBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public Builder addArgument(
                    int index, Rpc.Argument.Builder builderForValue) {
                if (argumentBuilder_ == null) {
                    ensureArgumentIsMutable();
                    argument_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    argumentBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public Builder addAllArgument(
                    Iterable<? extends Argument> values) {
                if (argumentBuilder_ == null) {
                    ensureArgumentIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, argument_);
                    onChanged();
                } else {
                    argumentBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public Builder clearArgument() {
                if (argumentBuilder_ == null) {
                    argument_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                    onChanged();
                } else {
                    argumentBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public Builder removeArgument(int index) {
                if (argumentBuilder_ == null) {
                    ensureArgumentIsMutable();
                    argument_.remove(index);
                    onChanged();
                } else {
                    argumentBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public Rpc.Argument.Builder getArgumentBuilder(
                    int index) {
                return getArgumentFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public Rpc.ArgumentOrBuilder getArgumentOrBuilder(
                    int index) {
                if (argumentBuilder_ == null) {
                    return argument_.get(index);
                } else {
                    return argumentBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public java.util.List<? extends ArgumentOrBuilder>
            getArgumentOrBuilderList() {
                if (argumentBuilder_ != null) {
                    return argumentBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(argument_);
                }
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public Rpc.Argument.Builder addArgumentBuilder() {
                return getArgumentFieldBuilder().addBuilder(
                        Rpc.Argument.getDefaultInstance());
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public Rpc.Argument.Builder addArgumentBuilder(
                    int index) {
                return getArgumentFieldBuilder().addBuilder(
                        index, Rpc.Argument.getDefaultInstance());
            }

            /**
             * <code>repeated .com.nscall.framework.protobuf.Argument argument = 3;</code>
             */
            public java.util.List<Argument.Builder>
            getArgumentBuilderList() {
                return getArgumentFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    Rpc.Argument, Rpc.Argument.Builder, Rpc.ArgumentOrBuilder>
            getArgumentFieldBuilder() {
                if (argumentBuilder_ == null) {
                    argumentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            Rpc.Argument, Rpc.Argument.Builder, Rpc.ArgumentOrBuilder>(
                            argument_,
                            ((bitField0_ & 0x00000004) == 0x00000004),
                            getParentForChildren(),
                            isClean());
                    argument_ = null;
                }
                return argumentBuilder_;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:com.nscall.framework.protobuf.CallRequest)
        }

    }

    /**
     * Protobuf type {@code com.nscall.framework.protobuf.Argument}
     */
    public static final class Argument extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.nscall.framework.protobuf.Argument)
            ArgumentOrBuilder {
        public static final int IDX_FIELD_NUMBER = 1;
        public static final int VALUE_FIELD_NUMBER = 2;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:com.nscall.framework.protobuf.Argument)
        private static final Rpc.Argument DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<Argument>
                PARSER = new com.google.protobuf.AbstractParser<Argument>() {
            public Argument parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Argument(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new Rpc.Argument();
        }

        private int idx_;
        private int value_;
        private byte memoizedIsInitialized = -1;

        // Use Argument.newBuilder() to construct.
        private Argument(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Argument() {
            idx_ = 0;
            value_ = 0;
        }

        private Argument(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            idx_ = input.readInt32();
                            break;
                        }
                        case 16: {

                            value_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Rpc.internal_static_com_nscall_framework_protobuf_Argument_descriptor;
        }

        public static Rpc.Argument parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Rpc.Argument parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Rpc.Argument parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Rpc.Argument parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Rpc.Argument parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Rpc.Argument parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Rpc.Argument parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Rpc.Argument parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Rpc.Argument parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Rpc.Argument parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Rpc.Argument parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Rpc.Argument parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Rpc.Argument prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static Rpc.Argument getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Argument> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Rpc.internal_static_com_nscall_framework_protobuf_Argument_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Rpc.Argument.class, Rpc.Argument.Builder.class);
        }

        /**
         * <code>int32 idx = 1;</code>
         */
        public int getIdx() {
            return idx_;
        }

        /**
         * <code>int32 value = 2;</code>
         */
        public int getValue() {
            return value_;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (idx_ != 0) {
                output.writeInt32(1, idx_);
            }
            if (value_ != 0) {
                output.writeInt32(2, value_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (idx_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, idx_);
            }
            if (value_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, value_);
            }
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Rpc.Argument)) {
                return super.equals(obj);
            }
            Rpc.Argument other = (Rpc.Argument) obj;

            boolean result = true;
            result = result && (getIdx()
                    == other.getIdx());
            result = result && (getValue()
                    == other.getValue());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + IDX_FIELD_NUMBER;
            hash = (53 * hash) + getIdx();
            hash = (37 * hash) + VALUE_FIELD_NUMBER;
            hash = (53 * hash) + getValue();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<Argument> getParserForType() {
            return PARSER;
        }

        public Rpc.Argument getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code com.nscall.framework.protobuf.Argument}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.nscall.framework.protobuf.Argument)
                Rpc.ArgumentOrBuilder {
            private int idx_;
            private int value_;

            // Construct using com.nscall.framework.protobuf.Rpc.Argument.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Rpc.internal_static_com_nscall_framework_protobuf_Argument_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Rpc.internal_static_com_nscall_framework_protobuf_Argument_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Rpc.Argument.class, Rpc.Argument.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                idx_ = 0;

                value_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Rpc.internal_static_com_nscall_framework_protobuf_Argument_descriptor;
            }

            public Rpc.Argument getDefaultInstanceForType() {
                return Rpc.Argument.getDefaultInstance();
            }

            public Rpc.Argument build() {
                Rpc.Argument result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Rpc.Argument buildPartial() {
                Rpc.Argument result = new Rpc.Argument(this);
                result.idx_ = idx_;
                result.value_ = value_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Rpc.Argument) {
                    return mergeFrom((Rpc.Argument) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Rpc.Argument other) {
                if (other == Rpc.Argument.getDefaultInstance()) return this;
                if (other.getIdx() != 0) {
                    setIdx(other.getIdx());
                }
                if (other.getValue() != 0) {
                    setValue(other.getValue());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Rpc.Argument parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Rpc.Argument) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>int32 idx = 1;</code>
             */
            public int getIdx() {
                return idx_;
            }

            /**
             * <code>int32 idx = 1;</code>
             */
            public Builder setIdx(int value) {

                idx_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 idx = 1;</code>
             */
            public Builder clearIdx() {

                idx_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>int32 value = 2;</code>
             */
            public int getValue() {
                return value_;
            }

            /**
             * <code>int32 value = 2;</code>
             */
            public Builder setValue(int value) {

                value_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 value = 2;</code>
             */
            public Builder clearValue() {

                value_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:com.nscall.framework.protobuf.Argument)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
