// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: search.proto

package protos

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SearchRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber           int32    `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32    `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{0}
}
func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *SearchRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

type SearchResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{1}
}
func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "co.wangming.nsb.samples.protobuf.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "co.wangming.nsb.samples.protobuf.SearchResponse")
}

func init() { proto.RegisterFile("search.proto", fileDescriptor_453745cff914010e) }

var fileDescriptor_453745cff914010e = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xc1, 0xaa, 0xc2, 0x30,
	0x10, 0x45, 0xe9, 0x7b, 0xb4, 0xe0, 0x68, 0x15, 0x82, 0x48, 0x77, 0x96, 0x2e, 0xa4, 0xab, 0x6c,
	0xfc, 0x0f, 0x29, 0xf5, 0x03, 0x4a, 0x52, 0xc6, 0x28, 0xb4, 0x49, 0x9a, 0x69, 0x10, 0xff, 0x5e,
	0x9a, 0xd4, 0xe5, 0x3d, 0xf7, 0x0e, 0x67, 0x60, 0x47, 0x28, 0x5c, 0xff, 0xe4, 0xd6, 0x99, 0xd9,
	0xb0, 0xb2, 0x37, 0xfc, 0x2d, 0xb4, 0x1a, 0x5f, 0x5a, 0x71, 0x4d, 0x92, 0x93, 0x18, 0xed, 0x80,
	0x14, 0x6b, 0xe9, 0x1f, 0x95, 0x86, 0xfc, 0x1e, 0x2e, 0x5a, 0x9c, 0x3c, 0xd2, 0xcc, 0x8e, 0x90,
	0x4e, 0x1e, 0xdd, 0xa7, 0x48, 0xca, 0xa4, 0xde, 0xb4, 0x31, 0xb0, 0x33, 0x6c, 0xad, 0x50, 0xd8,
	0x69, 0x3f, 0x4a, 0x74, 0xc5, 0x5f, 0x99, 0xd4, 0x69, 0x0b, 0x0b, 0xba, 0x05, 0xc2, 0x2e, 0x70,
	0x70, 0x48, 0x7e, 0x98, 0x3b, 0x8b, 0xae, 0x5b, 0x8a, 0xe2, 0x3f, 0x8c, 0xf2, 0x88, 0x1b, 0x74,
	0x8d, 0x50, 0x58, 0xd5, 0xb0, 0xff, 0xf9, 0xc8, 0x1a, 0x4d, 0xc8, 0x4e, 0x90, 0xc5, 0xc9, 0x6a,
	0x5c, 0x93, 0xcc, 0xc2, 0x8f, 0xd7, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x54, 0xb2, 0xb1,
	0xd2, 0x00, 0x00, 0x00,
}
