// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search.proto

package co.wangming.nsb.samples.protobuf;

public final class Search {
    private Search() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface SearchRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:co.wangming.nsb.samples.protobuf.SearchRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string query = 1;</code>
         *
         * @return The query.
         */
        java.lang.String getQuery();

        /**
         * <code>string query = 1;</code>
         *
         * @return The bytes for query.
         */
        com.google.protobuf.ByteString
        getQueryBytes();

        /**
         * <code>int32 page_number = 2;</code>
         *
         * @return The pageNumber.
         */
        int getPageNumber();

        /**
         * <code>int32 result_per_page = 3;</code>
         *
         * @return The resultPerPage.
         */
        int getResultPerPage();
    }

    /**
     * Protobuf type {@code co.wangming.nsb.samples.protobuf.SearchRequest}
     */
    public static final class SearchRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:co.wangming.nsb.samples.protobuf.SearchRequest)
            SearchRequestOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use SearchRequest.newBuilder() to construct.
        private SearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private SearchRequest() {
            query_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new SearchRequest();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private SearchRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            query_ = s;
                            break;
                        }
                        case 16: {

                            pageNumber_ = input.readInt32();
                            break;
                        }
                        case 24: {

                            resultPerPage_ = input.readInt32();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return co.wangming.nsb.samples.protobuf.Search.internal_static_co_wangming_nsb_samples_protobuf_SearchRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return co.wangming.nsb.samples.protobuf.Search.internal_static_co_wangming_nsb_samples_protobuf_SearchRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            co.wangming.nsb.samples.protobuf.Search.SearchRequest.class, co.wangming.nsb.samples.protobuf.Search.SearchRequest.Builder.class);
        }

        public static final int QUERY_FIELD_NUMBER = 1;
        private volatile java.lang.Object query_;

        /**
         * <code>string query = 1;</code>
         *
         * @return The query.
         */
        public java.lang.String getQuery() {
            java.lang.Object ref = query_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                query_ = s;
                return s;
            }
        }

        /**
         * <code>string query = 1;</code>
         *
         * @return The bytes for query.
         */
        public com.google.protobuf.ByteString
        getQueryBytes() {
            java.lang.Object ref = query_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                query_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PAGE_NUMBER_FIELD_NUMBER = 2;
        private int pageNumber_;

        /**
         * <code>int32 page_number = 2;</code>
         *
         * @return The pageNumber.
         */
        public int getPageNumber() {
            return pageNumber_;
        }

        public static final int RESULT_PER_PAGE_FIELD_NUMBER = 3;
        private int resultPerPage_;

        /**
         * <code>int32 result_per_page = 3;</code>
         *
         * @return The resultPerPage.
         */
        public int getResultPerPage() {
            return resultPerPage_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getQueryBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, query_);
            }
            if (pageNumber_ != 0) {
                output.writeInt32(2, pageNumber_);
            }
            if (resultPerPage_ != 0) {
                output.writeInt32(3, resultPerPage_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getQueryBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, query_);
            }
            if (pageNumber_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, pageNumber_);
            }
            if (resultPerPage_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, resultPerPage_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof co.wangming.nsb.samples.protobuf.Search.SearchRequest)) {
                return super.equals(obj);
            }
            co.wangming.nsb.samples.protobuf.Search.SearchRequest other = (co.wangming.nsb.samples.protobuf.Search.SearchRequest) obj;

            if (!getQuery()
                    .equals(other.getQuery())) return false;
            if (getPageNumber()
                    != other.getPageNumber()) return false;
            if (getResultPerPage()
                    != other.getResultPerPage()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + QUERY_FIELD_NUMBER;
            hash = (53 * hash) + getQuery().hashCode();
            hash = (37 * hash) + PAGE_NUMBER_FIELD_NUMBER;
            hash = (53 * hash) + getPageNumber();
            hash = (37 * hash) + RESULT_PER_PAGE_FIELD_NUMBER;
            hash = (53 * hash) + getResultPerPage();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(co.wangming.nsb.samples.protobuf.Search.SearchRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code co.wangming.nsb.samples.protobuf.SearchRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:co.wangming.nsb.samples.protobuf.SearchRequest)
                co.wangming.nsb.samples.protobuf.Search.SearchRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return co.wangming.nsb.samples.protobuf.Search.internal_static_co_wangming_nsb_samples_protobuf_SearchRequest_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return co.wangming.nsb.samples.protobuf.Search.internal_static_co_wangming_nsb_samples_protobuf_SearchRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                co.wangming.nsb.samples.protobuf.Search.SearchRequest.class, co.wangming.nsb.samples.protobuf.Search.SearchRequest.Builder.class);
            }

            // Construct using co.wangming.nsb.samples.protobuf.Search.SearchRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                query_ = "";

                pageNumber_ = 0;

                resultPerPage_ = 0;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return co.wangming.nsb.samples.protobuf.Search.internal_static_co_wangming_nsb_samples_protobuf_SearchRequest_descriptor;
            }

            @java.lang.Override
            public co.wangming.nsb.samples.protobuf.Search.SearchRequest getDefaultInstanceForType() {
                return co.wangming.nsb.samples.protobuf.Search.SearchRequest.getDefaultInstance();
            }

            @java.lang.Override
            public co.wangming.nsb.samples.protobuf.Search.SearchRequest build() {
                co.wangming.nsb.samples.protobuf.Search.SearchRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public co.wangming.nsb.samples.protobuf.Search.SearchRequest buildPartial() {
                co.wangming.nsb.samples.protobuf.Search.SearchRequest result = new co.wangming.nsb.samples.protobuf.Search.SearchRequest(this);
                result.query_ = query_;
                result.pageNumber_ = pageNumber_;
                result.resultPerPage_ = resultPerPage_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof co.wangming.nsb.samples.protobuf.Search.SearchRequest) {
                    return mergeFrom((co.wangming.nsb.samples.protobuf.Search.SearchRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(co.wangming.nsb.samples.protobuf.Search.SearchRequest other) {
                if (other == co.wangming.nsb.samples.protobuf.Search.SearchRequest.getDefaultInstance()) return this;
                if (!other.getQuery().isEmpty()) {
                    query_ = other.query_;
                    onChanged();
                }
                if (other.getPageNumber() != 0) {
                    setPageNumber(other.getPageNumber());
                }
                if (other.getResultPerPage() != 0) {
                    setResultPerPage(other.getResultPerPage());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                co.wangming.nsb.samples.protobuf.Search.SearchRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (co.wangming.nsb.samples.protobuf.Search.SearchRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object query_ = "";

            /**
             * <code>string query = 1;</code>
             *
             * @return The query.
             */
            public java.lang.String getQuery() {
                java.lang.Object ref = query_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    query_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string query = 1;</code>
             *
             * @return The bytes for query.
             */
            public com.google.protobuf.ByteString
            getQueryBytes() {
                java.lang.Object ref = query_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    query_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string query = 1;</code>
             *
             * @param value The query to set.
             * @return This builder for chaining.
             */
            public Builder setQuery(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                query_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string query = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearQuery() {

                query_ = getDefaultInstance().getQuery();
                onChanged();
                return this;
            }

            /**
             * <code>string query = 1;</code>
             *
             * @param value The bytes for query to set.
             * @return This builder for chaining.
             */
            public Builder setQueryBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                query_ = value;
                onChanged();
                return this;
            }

            private int pageNumber_;

            /**
             * <code>int32 page_number = 2;</code>
             *
             * @return The pageNumber.
             */
            public int getPageNumber() {
                return pageNumber_;
            }

            /**
             * <code>int32 page_number = 2;</code>
             *
             * @param value The pageNumber to set.
             * @return This builder for chaining.
             */
            public Builder setPageNumber(int value) {

                pageNumber_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 page_number = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearPageNumber() {

                pageNumber_ = 0;
                onChanged();
                return this;
            }

            private int resultPerPage_;

            /**
             * <code>int32 result_per_page = 3;</code>
             *
             * @return The resultPerPage.
             */
            public int getResultPerPage() {
                return resultPerPage_;
            }

            /**
             * <code>int32 result_per_page = 3;</code>
             *
             * @param value The resultPerPage to set.
             * @return This builder for chaining.
             */
            public Builder setResultPerPage(int value) {

                resultPerPage_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 result_per_page = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearResultPerPage() {

                resultPerPage_ = 0;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:co.wangming.nsb.samples.protobuf.SearchRequest)
        }

        // @@protoc_insertion_point(class_scope:co.wangming.nsb.samples.protobuf.SearchRequest)
        private static final co.wangming.nsb.samples.protobuf.Search.SearchRequest DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new co.wangming.nsb.samples.protobuf.Search.SearchRequest();
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<SearchRequest>
                PARSER = new com.google.protobuf.AbstractParser<SearchRequest>() {
            @java.lang.Override
            public SearchRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new SearchRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<SearchRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<SearchRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public co.wangming.nsb.samples.protobuf.Search.SearchRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface SearchResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:co.wangming.nsb.samples.protobuf.SearchResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string result = 1;</code>
         *
         * @return The result.
         */
        java.lang.String getResult();

        /**
         * <code>string result = 1;</code>
         *
         * @return The bytes for result.
         */
        com.google.protobuf.ByteString
        getResultBytes();
    }

    /**
     * Protobuf type {@code co.wangming.nsb.samples.protobuf.SearchResponse}
     */
    public static final class SearchResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:co.wangming.nsb.samples.protobuf.SearchResponse)
            SearchResponseOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use SearchResponse.newBuilder() to construct.
        private SearchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private SearchResponse() {
            result_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new SearchResponse();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private SearchResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            result_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return co.wangming.nsb.samples.protobuf.Search.internal_static_co_wangming_nsb_samples_protobuf_SearchResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return co.wangming.nsb.samples.protobuf.Search.internal_static_co_wangming_nsb_samples_protobuf_SearchResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            co.wangming.nsb.samples.protobuf.Search.SearchResponse.class, co.wangming.nsb.samples.protobuf.Search.SearchResponse.Builder.class);
        }

        public static final int RESULT_FIELD_NUMBER = 1;
        private volatile java.lang.Object result_;

        /**
         * <code>string result = 1;</code>
         *
         * @return The result.
         */
        public java.lang.String getResult() {
            java.lang.Object ref = result_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                result_ = s;
                return s;
            }
        }

        /**
         * <code>string result = 1;</code>
         *
         * @return The bytes for result.
         */
        public com.google.protobuf.ByteString
        getResultBytes() {
            java.lang.Object ref = result_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                result_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getResultBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, result_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getResultBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, result_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof co.wangming.nsb.samples.protobuf.Search.SearchResponse)) {
                return super.equals(obj);
            }
            co.wangming.nsb.samples.protobuf.Search.SearchResponse other = (co.wangming.nsb.samples.protobuf.Search.SearchResponse) obj;

            if (!getResult()
                    .equals(other.getResult())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + RESULT_FIELD_NUMBER;
            hash = (53 * hash) + getResult().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(co.wangming.nsb.samples.protobuf.Search.SearchResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code co.wangming.nsb.samples.protobuf.SearchResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:co.wangming.nsb.samples.protobuf.SearchResponse)
                co.wangming.nsb.samples.protobuf.Search.SearchResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return co.wangming.nsb.samples.protobuf.Search.internal_static_co_wangming_nsb_samples_protobuf_SearchResponse_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return co.wangming.nsb.samples.protobuf.Search.internal_static_co_wangming_nsb_samples_protobuf_SearchResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                co.wangming.nsb.samples.protobuf.Search.SearchResponse.class, co.wangming.nsb.samples.protobuf.Search.SearchResponse.Builder.class);
            }

            // Construct using co.wangming.nsb.samples.protobuf.Search.SearchResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                result_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return co.wangming.nsb.samples.protobuf.Search.internal_static_co_wangming_nsb_samples_protobuf_SearchResponse_descriptor;
            }

            @java.lang.Override
            public co.wangming.nsb.samples.protobuf.Search.SearchResponse getDefaultInstanceForType() {
                return co.wangming.nsb.samples.protobuf.Search.SearchResponse.getDefaultInstance();
            }

            @java.lang.Override
            public co.wangming.nsb.samples.protobuf.Search.SearchResponse build() {
                co.wangming.nsb.samples.protobuf.Search.SearchResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public co.wangming.nsb.samples.protobuf.Search.SearchResponse buildPartial() {
                co.wangming.nsb.samples.protobuf.Search.SearchResponse result = new co.wangming.nsb.samples.protobuf.Search.SearchResponse(this);
                result.result_ = result_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof co.wangming.nsb.samples.protobuf.Search.SearchResponse) {
                    return mergeFrom((co.wangming.nsb.samples.protobuf.Search.SearchResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(co.wangming.nsb.samples.protobuf.Search.SearchResponse other) {
                if (other == co.wangming.nsb.samples.protobuf.Search.SearchResponse.getDefaultInstance()) return this;
                if (!other.getResult().isEmpty()) {
                    result_ = other.result_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                co.wangming.nsb.samples.protobuf.Search.SearchResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (co.wangming.nsb.samples.protobuf.Search.SearchResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object result_ = "";

            /**
             * <code>string result = 1;</code>
             *
             * @return The result.
             */
            public java.lang.String getResult() {
                java.lang.Object ref = result_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    result_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string result = 1;</code>
             *
             * @return The bytes for result.
             */
            public com.google.protobuf.ByteString
            getResultBytes() {
                java.lang.Object ref = result_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    result_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string result = 1;</code>
             *
             * @param value The result to set.
             * @return This builder for chaining.
             */
            public Builder setResult(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                result_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string result = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearResult() {

                result_ = getDefaultInstance().getResult();
                onChanged();
                return this;
            }

            /**
             * <code>string result = 1;</code>
             *
             * @param value The bytes for result to set.
             * @return This builder for chaining.
             */
            public Builder setResultBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                result_ = value;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:co.wangming.nsb.samples.protobuf.SearchResponse)
        }

        // @@protoc_insertion_point(class_scope:co.wangming.nsb.samples.protobuf.SearchResponse)
        private static final co.wangming.nsb.samples.protobuf.Search.SearchResponse DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new co.wangming.nsb.samples.protobuf.Search.SearchResponse();
        }

        public static co.wangming.nsb.samples.protobuf.Search.SearchResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<SearchResponse>
                PARSER = new com.google.protobuf.AbstractParser<SearchResponse>() {
            @java.lang.Override
            public SearchResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new SearchResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<SearchResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<SearchResponse> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public co.wangming.nsb.samples.protobuf.Search.SearchResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_co_wangming_nsb_samples_protobuf_SearchRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_co_wangming_nsb_samples_protobuf_SearchRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_co_wangming_nsb_samples_protobuf_SearchResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_co_wangming_nsb_samples_protobuf_SearchResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\014search.proto\022 co.wangming.nsb.samples." +
                        "protobuf\"L\n\rSearchRequest\022\r\n\005query\030\001 \001(\t" +
                        "\022\023\n\013page_number\030\002 \001(\005\022\027\n\017result_per_page" +
                        "\030\003 \001(\005\" \n\016SearchResponse\022\016\n\006result\030\001 \001(\t" +
                        "b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_co_wangming_nsb_samples_protobuf_SearchRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_co_wangming_nsb_samples_protobuf_SearchRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_co_wangming_nsb_samples_protobuf_SearchRequest_descriptor,
                new java.lang.String[]{"Query", "PageNumber", "ResultPerPage",});
        internal_static_co_wangming_nsb_samples_protobuf_SearchResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_co_wangming_nsb_samples_protobuf_SearchResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_co_wangming_nsb_samples_protobuf_SearchResponse_descriptor,
                new java.lang.String[]{"Result",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
