// source: search.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.co.wangming.nsb.samples.protobuf.SearchRequest', null, global);
goog.exportSymbol('proto.co.wangming.nsb.samples.protobuf.SearchResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.co.wangming.nsb.samples.protobuf.SearchRequest = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.co.wangming.nsb.samples.protobuf.SearchRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.co.wangming.nsb.samples.protobuf.SearchRequest.displayName = 'proto.co.wangming.nsb.samples.protobuf.SearchRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.co.wangming.nsb.samples.protobuf.SearchResponse = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.co.wangming.nsb.samples.protobuf.SearchResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.co.wangming.nsb.samples.protobuf.SearchResponse.displayName = 'proto.co.wangming.nsb.samples.protobuf.SearchResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.co.wangming.nsb.samples.protobuf.SearchRequest.prototype.toObject = function (opt_includeInstance) {
        return proto.co.wangming.nsb.samples.protobuf.SearchRequest.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.co.wangming.nsb.samples.protobuf.SearchRequest} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.co.wangming.nsb.samples.protobuf.SearchRequest.toObject = function (includeInstance, msg) {
        var f, obj = {
            query: jspb.Message.getFieldWithDefault(msg, 1, ""),
            pageNumber: jspb.Message.getFieldWithDefault(msg, 2, 0),
            resultPerPage: jspb.Message.getFieldWithDefault(msg, 3, 0)
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.co.wangming.nsb.samples.protobuf.SearchRequest}
 */
proto.co.wangming.nsb.samples.protobuf.SearchRequest.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.co.wangming.nsb.samples.protobuf.SearchRequest;
    return proto.co.wangming.nsb.samples.protobuf.SearchRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.co.wangming.nsb.samples.protobuf.SearchRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.co.wangming.nsb.samples.protobuf.SearchRequest}
 */
proto.co.wangming.nsb.samples.protobuf.SearchRequest.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {string} */ (reader.readString());
                msg.setQuery(value);
                break;
            case 2:
                var value = /** @type {number} */ (reader.readInt32());
                msg.setPageNumber(value);
                break;
            case 3:
                var value = /** @type {number} */ (reader.readInt32());
                msg.setResultPerPage(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.co.wangming.nsb.samples.protobuf.SearchRequest.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.co.wangming.nsb.samples.protobuf.SearchRequest.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.co.wangming.nsb.samples.protobuf.SearchRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.co.wangming.nsb.samples.protobuf.SearchRequest.serializeBinaryToWriter = function (message, writer) {
    var f = undefined;
    f = message.getQuery();
    if (f.length > 0) {
        writer.writeString(
            1,
            f
        );
    }
    f = message.getPageNumber();
    if (f !== 0) {
        writer.writeInt32(
            2,
            f
        );
    }
    f = message.getResultPerPage();
    if (f !== 0) {
        writer.writeInt32(
            3,
            f
        );
    }
};


/**
 * optional string query = 1;
 * @return {string}
 */
proto.co.wangming.nsb.samples.protobuf.SearchRequest.prototype.getQuery = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.co.wangming.nsb.samples.protobuf.SearchRequest} returns this
 */
proto.co.wangming.nsb.samples.protobuf.SearchRequest.prototype.setQuery = function (value) {
    return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 page_number = 2;
 * @return {number}
 */
proto.co.wangming.nsb.samples.protobuf.SearchRequest.prototype.getPageNumber = function () {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.co.wangming.nsb.samples.protobuf.SearchRequest} returns this
 */
proto.co.wangming.nsb.samples.protobuf.SearchRequest.prototype.setPageNumber = function (value) {
    return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 result_per_page = 3;
 * @return {number}
 */
proto.co.wangming.nsb.samples.protobuf.SearchRequest.prototype.getResultPerPage = function () {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.co.wangming.nsb.samples.protobuf.SearchRequest} returns this
 */
proto.co.wangming.nsb.samples.protobuf.SearchRequest.prototype.setResultPerPage = function (value) {
    return jspb.Message.setProto3IntField(this, 3, value);
};


if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.co.wangming.nsb.samples.protobuf.SearchResponse.prototype.toObject = function (opt_includeInstance) {
        return proto.co.wangming.nsb.samples.protobuf.SearchResponse.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.co.wangming.nsb.samples.protobuf.SearchResponse} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.co.wangming.nsb.samples.protobuf.SearchResponse.toObject = function (includeInstance, msg) {
        var f, obj = {
            result: jspb.Message.getFieldWithDefault(msg, 1, "")
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.co.wangming.nsb.samples.protobuf.SearchResponse}
 */
proto.co.wangming.nsb.samples.protobuf.SearchResponse.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.co.wangming.nsb.samples.protobuf.SearchResponse;
    return proto.co.wangming.nsb.samples.protobuf.SearchResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.co.wangming.nsb.samples.protobuf.SearchResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.co.wangming.nsb.samples.protobuf.SearchResponse}
 */
proto.co.wangming.nsb.samples.protobuf.SearchResponse.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {string} */ (reader.readString());
                msg.setResult(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.co.wangming.nsb.samples.protobuf.SearchResponse.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.co.wangming.nsb.samples.protobuf.SearchResponse.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.co.wangming.nsb.samples.protobuf.SearchResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.co.wangming.nsb.samples.protobuf.SearchResponse.serializeBinaryToWriter = function (message, writer) {
    var f = undefined;
    f = message.getResult();
    if (f.length > 0) {
        writer.writeString(
            1,
            f
        );
    }
};


/**
 * optional string result = 1;
 * @return {string}
 */
proto.co.wangming.nsb.samples.protobuf.SearchResponse.prototype.getResult = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.co.wangming.nsb.samples.protobuf.SearchResponse} returns this
 */
proto.co.wangming.nsb.samples.protobuf.SearchResponse.prototype.setResult = function (value) {
    return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.co.wangming.nsb.samples.protobuf);
